import { useEffect, useState } from "react";
import Head from "next/head";

import styles from "../styles/Home.module.css";
import {
  useQuery,
  useQueryClient,
  useMutation,
  QueryClient,
  QueryClientProvider,
} from "react-query";

import { useTeamSeasDonations } from "../hooks/useTeamSeasDonations";

export default function Home() {
  const { status, data, error, isFetching } = useTeamSeasDonations();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
    </div>
  );
}
