import { useEffect, useState } from "react";
import Head from "next/head";
import ProgressBar from "../components/ProgressBar";

import styles from "../styles/Home.module.css";

import { useTeamSeasDonations } from "../hooks/useTeamSeasDonations";

export default function Home() {
  const { status, data, error, isFetching } = useTeamSeasDonations();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ProgressBar></ProgressBar>
        {data &&
          data.map((item, index) => (
            <div key={index}>
              <p>{item.display_name}</p>
              <p>{item.message_public}</p>
              <p>{item.donation}</p>
            </div>
          ))}
      </main>
    </div>
  );
}
